🔀 :: (#1) 토스트 만들기
DMS-ONE/AndroidMaster pull request #2
Opened 2023-05-18 14:30 UTC by parkuiery

## 작업 사항
- EditText 구현
- Button 구현
- Button 클릭 시 EditText 에서 text 받아와서 토스트 표시

2023-05-18 14:36 UTC, Tmdhoon2 requested changes

2023-05-18 14:36 UTC, Tmdhoon2 commented on RecyclerViewExample/app/src/main/java/com/example/recyclerviewexample/SecoundActivity.java
> +                Toast.makeText(SecoundActivity.this, "Input : " + inputText, Toast.LENGTH_SHORT).show();
여기 v.getContext() 이런식으로 작성하는게 좋을 것 같아요

2023-05-18 14:36 UTC, Tmdhoon2 commented on RecyclerViewExample/app/src/main/java/com/example/recyclerviewexample/MainActivity.java
> +    @SuppressLint({"MissingInflatedId", "WrongViewCast"})
이거 지워주세요 + import

2023-05-19 11:08 UTC, parkuiery commented on RecyclerViewExample/app/src/main/java/com/example/recyclerviewexample/SecoundActivity.java
> +                Toast.makeText(SecoundActivity.this, "Input : " + inputText, Toast.LENGTH_SHORT).show();
수정 했습니다

2023-05-19 11:08 UTC, parkuiery commented on RecyclerViewExample/app/src/main/java/com/example/recyclerviewexample/MainActivity.java
> +    @SuppressLint({"MissingInflatedId", "WrongViewCast"})
수정 했습니다

2023-05-19 11:18 UTC, Tmdhoon2 approved these changes

2023-05-19 11:20 UTC, merged

2023-05-19 11:20 UTC, chlgkdms commented on RecyclerViewExample/app/src/main/java/com/example/recyclerviewexample/MainActivity.java
> +import android.widget.Toast;
필요 없는 import 안 지워져 있어요