🔀 :: (#3) 리사이클러뷰 아이템 추가 기능 구현
DMS-ONE/AndroidMaster pull request #4
Opened 2023-05-21 14:37 UTC by parkuiery

### 작업사항
-버튼 클릭 시 아이템 추가

2023-05-22 23:50 UTC, Tmdhoon2 requested changes

2023-05-22 23:50 UTC, Tmdhoon2 commented on RecyclerViewExample/app/src/main/java/com/example/recyclerviewexample/MainActivity.java
> +        adapter = new MainAdapter(itemList);
생성자를 알면 코드가 보일거에요

2023-05-22 23:50 UTC, Tmdhoon2 commented on RecyclerViewExample/app/src/main/java/com/example/recyclerviewexample/MainActivity.java
> +        adapter.notifyDataSetChanged();
notifyDataSetChanged 가 리사이클러뷰에서 itemList 가 변경된 경우에 어댑터를 업데이트해서 변경된 데이터를 리사이클러뷰에 반영해주는 함순데, adapter 를 업데이트 해주는 함수가 여러개 있어요. 한 번 알아보는거 추천합니당

2023-05-22 23:50 UTC, Tmdhoon2 approved these changes

2023-05-23 00:01 UTC, chlgkdms commented on RecyclerViewExample/app/src/main/res/layout/activity_main.xml
>          app:layout_constraintTop_toBottomOf="@+id/textView2"
이 textView2 네이밍 좀 바꿔주시면 좋을 것 같아요

2023-05-23 00:36 UTC, merged