(#6)secondactivity viewbinding 사용하기
DMS-ONE/AndroidMaster pull request #7
Opened 2023-05-23 08:20 UTC by parkuiery

###secondactivity에서 viewbinding 사용하기
-findviewbyid 코드를 viewbinding코드로 고치기

2023-05-23 22:21 UTC, Tmdhoon2 requested changes

2023-05-23 22:21 UTC, Tmdhoon2 commented on RecyclerViewExample/app/src/main/java/com/example/recyclerviewexample/MainAdapter.java
> +=======
여기 stash 꼬이면서 생긴건데 없애야 될 것 같아요

2023-05-23 22:24 UTC, Tmdhoon2 commented on RecyclerViewExample/app/src/main/java/com/example/recyclerviewexample/MainAdapter.java
> +=======
그리고 보통 pr 날리기 전에는 앱을 한 번 실행시켜서 오류가 없는지 확인합니다. 왜냐하면 main 브랜치는 나중에 배포와 연관되어지는 브랜치기 때문에 정상적으로 작동하는 코드들만 올려야 해요

2023-06-02 05:55 UTC, chlgkdms commented on RecyclerViewExample/app/build.gradle
> +    }
viewBinding = true 이렇게 코드 수정해주세요!

2023-06-08 14:09 UTC, parkuiery commented on RecyclerViewExample/app/src/main/java/com/example/recyclerviewexample/MainAdapter.java
> +=======
고쳤습니다

2023-06-08 14:09 UTC, parkuiery commented on RecyclerViewExample/app/build.gradle
> +    }
고쳤습니다

2023-06-11 06:54 UTC, Tmdhoon2 approved these changes

2023-06-12 00:00 UTC, merged